name: "AutoIndex Work Environment Data"
description: "Automatically update an HTML index of work environment data."
inputs:
  github_token:
    description: "The GitHub token to use for deployment."
    required: true
  year:
    description: "The year the data is for."
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        run_install: true
        version: 10

    - run: pnpm install
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: pnpm latest ${{ github.workspace }}/db.sqlite ${{ github.action_path }}/public/data.json
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: pnpm build
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        NEXT_PUBLIC_YEAR: ${{ inputs.year }}
        SOURCE_DIRECTORY_PATH: ${{ github.workspace }}

    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ${{ github.action_path }}/out
        force_orphan: true
